# Generated by Django 3.2.5 on 2021-09-19 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('display_author', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('img_0', models.ImageField(default=0, upload_to='pics')),
                ('img_1', models.ImageField(default=0, upload_to='pics')),
                ('img_2', models.ImageField(default=0, upload_to='pics')),
                ('img_3', models.ImageField(default=0, upload_to='pics')),
                ('img_4', models.ImageField(default=0, upload_to='pics')),
                ('img_5', models.ImageField(default=0, upload_to='pics')),
                ('img_6', models.ImageField(default=0, upload_to='pics')),
                ('img_7', models.ImageField(default=0, upload_to='pics')),
                ('img_8', models.ImageField(default=0, upload_to='pics')),
                ('img_9', models.ImageField(default=0, upload_to='pics')),
                ('video', models.FileField(default=0, upload_to='videos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
